apiVersion: v1
kind: Service
metadata:
  name: pet-frontend
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: pet-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
