apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-backend
  namespace: petngo 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pet-backend
  template:
    metadata:
      labels:
        app: pet-backend
    spec:
      containers:
        - name: pet-backend
          image: adi2634/pet-backend:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /app/petback/config.json
              subPath: config.json
            - name: backend-pv
              mountPath: /opt/
      volumes:
        - name: config-volume
          secret:
            secretName: backend-config-secret
        - name: backend-pv
          persistentVolumeClaim:
            claimName: backend-pvc
