apiVersion: v1
kind: Service
metadata:
  name: pet-backend
  namespace: petngo
spec:
  selector:
    app: pet-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer 