apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-frontend
  namespace: petngo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-frontend
  template:
    metadata:
      labels:
        app: pet-frontend
    spec:
      containers:
        - name: pet-frontend
          image: adi2634/pet-frontend:latest
          imagePullPolicy:
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config-volume
              mountPath: /app/petfront/config/config.json
              subPath: config.json
          resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 200m
              memory: 500M
      volumes:
        - name: config-volume
          secret:
            secretName: frontend-config-secret
  
