apiVersion: v1
kind: Pod
metadata:
  name: demo-init-container
spec:
  containers:
  - name: main-app
    image: nginx
    ports:
    - containerPort: 80

  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'echo "Initializing..."; sleep 5']