apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:          #backend pv
    path: /mnt/data/backend
  storageClassName: standard
  claimRef:
    name: backend-pvc        # PVC name
    namespace: petngo